CREATE TABLE IF NOT EXISTS `form_progress_note` (
    `id` bigint(20) NOT NULL auto_increment,
    `date` datetime default NULL,
    `pid` bigint(20) default 0,
    `user` varchar(255) default NULL,
    `groupname` varchar(255) default NULL,
    `authorized` tinyint(4) default 0,
    `activity` tinyint(4) default 0,
    `datedata` datetime,
    `starttime` text,
    `endtime` text,
    `facetofacetime` text,
    `setting` text,
    `mode` text,
    `attendant` text,
    `focusofsession` text,
    `ded` tinyint(4) DEFAULT NULL,
    `iicp` tinyint(4) DEFAULT NULL,
    `iar` tinyint(4) DEFAULT NULL,
    `dtr` tinyint(4) DEFAULT NULL,
    `ppg` tinyint(4) DEFAULT NULL,
    `pgal` tinyint(4) DEFAULT NULL,
    `bcs` tinyint(4) DEFAULT NULL,
    `goaladdressed` text,
    `goaladdressed2` text,
    `goaladdressed3` text,
    `situation` text,
    `intevntion` text,
    `progressbarrier` text,
    `plane` text,
    `signaaturetitle` text,
    `supervisorgignaturetitle` text,
PRIMARY KEY (id)
) ENGINE=InnoDB;