CREATE TABLE IF NOT EXISTS form_individual_treatment_plan (
id bigint(20) NOT NULL auto_increment,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
date_of_referal date default NULL,
dcn varchar(200) default NULL,
icd9 varchar(5) default NULL,
prognosis varchar(20) default NULL,
diagnosis_description longtext DEFAULT NULL,
presenting_problem longtext DEFAULT NULL,
frequency varchar(10) default NULL,
duration varchar(10) default NULL,
short_goal1_date date default NULL,
short_term_goals_1 varchar(200) default NULL,
short_goal1_current_behave VARCHAR(255) default NULL,
short_goal1_method_individual INT(1) DEFAULT NULL,
short_goal1_method_family INT(1) DEFAULT NULL,
short_goal1_method_group INT(1) DEFAULT NULL,
short_goal1_method_parenting INT(1) DEFAULT NULL,
short_goal1_frequency VARCHAR(25) DEFAULT NULL,
short_goal1_duration VARCHAR(25) DEFAULT NULL,
short_goal1_responsible VARCHAR(25) DEFAULT NULL,
short_goal1_resolved VARCHAR(25) DEFAULT NULL,
short_goal1_discontinued VARCHAR(25) DEFAULT NULL,
short_goal2_date date NULL,
short_term_goals_2 varchar(200) default NULL,
short_goal2_current_behave VARCHAR(255) default NULL,
short_goal2_method_individual INT(1) DEFAULT NULL,
short_goal2_method_family INT(1) DEFAULT NULL,
short_goal2_method_group INT(1) DEFAULT NULL,
short_goal2_method_parenting INT(1) DEFAULT NULL,
short_goal2_frequency VARCHAR(25) DEFAULT NULL,
short_goal2_duration VARCHAR(25) DEFAULT NULL,
short_goal2_responsible VARCHAR(25) DEFAULT NULL,
short_goal2_resolved VARCHAR(25) DEFAULT NULL,
short_goal2_discontinued VARCHAR(25) DEFAULT NULL,
short_goal3_date date NULL,
short_term_goals_3 varchar(200) default NULL,
short_goal3_current_behave VARCHAR(255) default NULL,
short_goal3_method_individual INT(1) DEFAULT NULL,
short_goal3_method_family INT(1) DEFAULT NULL,
short_goal3_method_group INT(1) DEFAULT NULL,
short_goal3_method_parenting INT(1) DEFAULT NULL,
short_goal3_frequency VARCHAR(25) DEFAULT NULL,
short_goal3_duration VARCHAR(25) DEFAULT NULL,
short_goal3_responsible VARCHAR(25) DEFAULT NULL,
short_goal3_resolved VARCHAR(25) DEFAULT NULL,
short_goal3_discontinued VARCHAR(25) DEFAULT NULL,
misc_data TEXT DEFAULT NULL;
PRIMARY KEY (id)
) ENGINE=InnoDB;
